name: netmasha_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_rate_limiter: ^1.0.1
  content_length_validator: ^1.2.1
  shelf_helmet: ^2.2.0
  shelf_cors_headers: ^0.1.5
  supabase: ^2.0.2
  dart_jsonwebtoken: ^2.12.1
  shelf_hotreload: ^1.4.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
